blog/urls.py
from django.urls import path
from .views import (
    DraftListView,
    PostListView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)
from . import views

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<slug:slug>/', views.post_detail, name='post-detail'),
    path('drafts/', DraftListView.as_view(), name='draft-list'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('like/', views.post_like, name='like'),
    path('readinglist/', views.liked_post, name='liked-post'),
    path('about/', views.about, name='blog-about'),
]

django_site/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from blog.views import PostListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PostListView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

# The static() helper function is suitable for development but not for production use.
# Django is very inefficient at serving static files. Never serve your static files with Django
# in a production environment. You will learn how to serve static files in a production environment
# in Chapter 17, Going Live.

blog/models.py
from enum import auto
from django.conf import settings
from django.db import models
from django.db.models.functions import Now
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils import timezone
from users.models import CustomUser
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class DraftManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.DRAFT)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, null=False, unique=True)
    content = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )
    status = models.CharField(
        max_length=2,
        choices=Status.choices,
        default=Status.DRAFT
    )
    objects = models.Manager()
    published = PublishedManager()
    draft = DraftManager()
    tags = TaggableManager()
    users_like = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='post_liked',
        blank=True
    )
    post_image = models.ImageField(upload_to='post_pics')

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post-detail', kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import JsonResponse
from django.urls import reverse_lazy
from users.models import CustomUser
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Post, Comment
from .forms import CommentForm


def home_redirect(request):
    return render(request, 'blog/home.html')


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-publish']
    paginate_by = 5

    def get_queryset(self):
        return Post.published.all()


class DraftListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/draft_list.html'
    context_object_name = 'posts'
    ordering = ['-created_at']

    def get_queryset(self):
        return Post.draft.filter(author=self.request.user)


class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(
            CustomUser, username=self.kwargs.get('username')
        )
        return Post.published.filter(author=user).order_by('-publish')


def post_detail(request, slug):
    post = get_object_or_404(
        Post,
        slug=slug,
        status=Post.Status.PUBLISHED,
    )

    comments = post.comments.filter(active=True)
    form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-publish')[:4]

    return render(
        request,
        'blog/post_detail.html',
        {
            'post': post,
            'comments': comments,
            'form': form,
            'similar_posts': similar_posts
        }
    )


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'post_image', 'tags']
    template_name = 'blog/post_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        status = self.request.POST.get('status', 'DF')
        if status not in dict(Post.Status.choices):
            status = 'DF'
        form.instance.status = status
        return super().form_valid(form)

    def get_success_url(self):
        if self.object.status == 'DF':
            return reverse_lazy('blog:draft-list')
        return reverse_lazy('blog:post-detail', kwargs={'slug': self.object.slug})


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content', 'post_image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    # To prevent users from updating other people's posts
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/blog/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, 'blog/about.html')


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        pk=post_id,
        status=Post.Status.PUBLISHED
    )
    comment = None
    form = CommentForm(data=request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
        return redirect('blog:post-detail', slug=post.slug)
    return render(
        request,
        'blog/comment.html',
        {
            'post': post,
            'form': form,
            'comment': comment
        }
    )


@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = Post.published.get(id=post_id)
            if action == 'like':
                post.users_like.add(request.user)
            else:
                post.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Post.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})


@login_required
def liked_post(request):
    liked_posts = Post.objects.filter(users_like=request.user)
    return render(
        request,
        'blog/readinglist.html',
        {'liked_posts': liked_posts}
    )

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}
  <h1>About</h1>
{% endblock  %}

blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://bootswatch.com/5/lux/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

  {% if title %}
    <title>Django Blog - {{ title }}</title>
  {% else %}
    <title>Django Blog</title>
  {% endif %}
  
</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container-fluid px-4 d-flex justify-content-between">
        <a class="navbar-brand fw-bold fs-4" href="{% url 'blog:home' %}">Travelog</a>
        
        <div class="ms-auto d-flex align-items-center">
          {% if user.is_authenticated %}
            <div class="dropdown">
              <a class="dropdown-toggle d-flex align-items-center" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{% thumbnail request.user.profile.photo 100x100 crop %}" 
                      class="rounded-circle avatar"
                      alt="avatar">
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                <li><a class="dropdown-item" href="{% url 'blog:post-create' %}">Create Post</a></li>
                <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:liked-post' %}">Reading List</a></li>
                <li><hr class="dropdown-divider"></li>
                <li>
                  <form method="post" action="{% url "logout" %}" class="d-inline">
                    {% csrf_token %}
                    <button class="dropdown-item" type="submit"><i class="fa-solid fa-right-from-bracket me-2"></i>Logout</button>
                  </form>
                </li>
              </ul>
            </div>
          {% else %}
            <a class="btn btn-outline-success me-2" href="{% url 'login' %}">Login</a>
            <a class="btn btn-outline-success" href="{% url 'register' %}">Register</a>
          {% endif %}
        </div>
      </div>
    </nav>
  </header>

  <main role="main">
    {% block content %}{% endblock %}  
  </main>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/a4f7e3b211.js" crossorigin="anonymous"></script>
  <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>
  <script>
    const csrftoken = Cookies.get('csrftoken');
    document.addEventListener('DOMContentLoaded', (event) => {
      {% block domready %}
      {% endblock %}
    })
  </script>
</body>
</html>

blog/templates/blog/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock  %}

{% block content %}
  <div class="content-section">
    {% if comment %}
      <h2>Your comment has been added.</h2>
      <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
      {% include "blog/includes/comment_form.html" %}
    {% endif %}
  </div>
{% endblock  %}

blog/templates/blog/draft_list.html
{% extends "blog/base.html" %}
{% load thumbnail %}
{% load social_share %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  {% if posts %}
      {% for post in posts %}
          <article class="media content-section d-flex mb-4 px-5 pt-4">
            <img src="{% thumbnail post.author.profile.photo 300x300 crop  %}" class="rounded-circle avatar mt-2 me-3">
            <div class="media-body">
              <div class="article-metadata mt-2 d-flex justify-content-between align-items-center">
                <div>
                  <p class="author"><a class="mt-4" href="{{ post.get_absolute_url }}">{{ post.author.username }}</a></p>
                  <small class="text-muted">{{ post.publish|date:'d M Y' }}</small>
                </div>
                {% if post.author == user %}
                <div>
                  <a class="btn btn-warning btn-md my-2" href="{% url "blog:post-update" post.id %}">Edit</a>
                </div>
                {% endif %}
              </div>
              
        
              <h3 class="mt-2">{{ post.title }}</h3>
              {% if post.tags.all %}
                <p class="article-content fw-light">Tags: {{ post.tags.all|join:", " }}</p>
              {% endif %}
              {% if post.post_image %}
                <img src="{% thumbnail post.post_image 600x400 %}" class="img-fluid mb-4 rounded">
              {% endif %}
              <p class="article-content">{{ post.content|truncatewords:30 }}</p>
            
            </div>
          </article>
      {% endfor %}
  {% endif %}
{% endblock  %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load thumbnail %}

{% block content %}
  <section class="banner text-center">
    <div class="banner-content">
      <h1 class="banner-heading fw-bold">Looking for Your Next Adventure?</h1>
      <p class="banner-subheading">Join a community of travelers and share your journey.</p>
      <a href="#cta" class="btn btn-outline-light btn-md">Get Started</a>
    </div>
  </section>

  <div class="container">
    <div class="pt-3">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    </div>
    <div class="album py-5">
      <div class="container text-center">
        <h2 class="album-heading">Latest Posts</h2>
      </div>
      <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
          {% for post in posts %}
            <div class="col">
              <div class="card h-100 shadow-sm">
                <div class="">
                  <img class="card-img-top" src="{{ post.post_image.url }}" alt="blog-thumbnail">
                </div>
                <div class="card-body d-flex flex-column">
                  <h4><a class="card-title stretched-link text-dark" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
                  <p class="card-text flex-grow-1">{{ post.content|truncatewords:15 }}</p>
                  <div class="border-top pt-2 d-flex justify-content-between align-items-center text-end">
                    <img src="{% thumbnail post.author.profile.photo 50x50 crop  %}" class="rounded-circle avatar mt-2 me-2" width="40" height="40">
                    <div>
                      <p class="author">
                        <a href="{% url 'blog:user-posts' post.author.username %}">{{ post.author.username }}</a>
                      </p>
                      <small class="text-muted">{{ post.publish|date:'d M Y' }}</small>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    
    {% if is_paginated %}
      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a> 
      {% endif %}
  
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}
  
      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a> 
      {% endif %}
    {% endif %} 
  </div>
  
{% endblock  %}

blog/templates/blog/latest_posts.html
<ul class="list-inline">
  {% for post in latest_posts %}
    <li>
      <a class="link-primary" href="{{ post.get_absolute_url }}">{{ post.title}}</a>
    </li>
  {% endfor %}
</ul>

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block title %}Delete Post{% endblock  %}

{% block content %}
  <div class="content-section">
    <form method="post">  
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Delete Post</legend>
        <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-danger mb-3" type="submit">Yes, Delete</button>
        <a class="btn btn-outline-secondary mb-3" href="{{ post.get_absolute_url }}">Cancel</a>

      </div>
    </form>
  </div>
{% endblock  %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load thumbnail %}
{% load social_share %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <article class="media content-section d-flex mb-4">
    <img src="{% thumbnail post.author.profile.photo 300x300 crop  %}" class="rounded-circle avatar mt-2 me-3">
    <div class="media-body">
      <div class="article-metadata mt-2 d-flex justify-content-between align-items-center">
        <div>
          <p class="author"><a class="mt-4" href="{{ post.get_absolute_url }}">{{ post.author.username }}</a></p>
          <small class="text-muted">{{ post.publish|date:'d M Y' }}</small>
          {% if post.author == user %}
            <div>
              <a class="btn btn-secondary btn-sm my-2" href="{% url "blog:post-update" post.id %}">Update</a>
              <a class="btn btn-danger btn-sm my-2" href="{% url "blog:post-delete" post.id %}">Delete</a>
            </div>
          {% endif %}
        </div>
      
        <div class="buttons-wrapper d-flex align-items-center gap-3">
          {% with total_likes=post.users_like.count users_like=post.users_like.all %}    
              <a href="#" data-id="{{ post.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like-btn link-primary">
                <i class="
                  {% if request.user not in users_like %}
                    fa-regular
                  {% else %}
                    fa-solid
                  {% endif %} fa-bookmark fa-lg"></i><span class="total ms-1"> {{ total_likes }}</span>
              </a>
          {% endwith %}
          {% post_to_facebook object_or_url %}
          {% post_to_twitter object_or_url %}
          <a href="https://www.linkedin.com/sharing/share-offsite/?url={{ post.get_absolute_url }}" 
            target="_blank" 
            rel="noopener noreferrer" 
            class="link-primary">
            <i class="fa-brands fa-linkedin fa-lg"></i>
          </a>
        </div>
      </div>
      <div class="article-metadata mb-4">
        <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
        <p class="article-content fw-light">Tags: {{ post.tags.all|join:", " }}</p>
        {% if post.post_image %}
          <img src="{% thumbnail post.post_image 700x500 %}" class="img-fluid mb-4 rounded">
        {% endif %}
        <p class="article-content">{{ post.content }}</p>
      </div>
    </div>
  </article>

  <div class="container mb-5">
    <h3 class="mb-4">Simliar Posts</h3>
    <div class="d-flex flex-column">
    {% for post in similar_posts %}
        <h5><a class="link-secondary" href="{{ post.get_absolute_url}}">{{ post.title }}</a></h5>
    {% empty %}
      There are no similar posts yet.
    {% endfor %}
    </div>
  </div>

  {% with comments.count as total_comments %}
    <div class="container mb-5">
      <h3 class="mb-4">Comment{{ total_comments|pluralize }} ({{ total_comments }})</h3>
      {% for comment in comments %}
        <div class="media mb-4">
          <div class="media-body d-flex flex-row gap-2">
            <p class="mb-0"><strong>{{ comment.name }}</strong></p>
            <p class="text-muted mb-0"> {{ comment.created|date:'d M Y' }}</p>
          </div>
          <div class="media-body border-bottom">
            <p>{{ comment.body|linebreaks }}</p>
          </div>
        </div>
      {% empty %}
        <p>No comments yet</p>
      {% endfor %}
    </div>
    {% include "blog/includes/comment_form.html" %}
  {% endwith %}
{% endblock  %}

{% block domready %}
    const url = '{% url "blog:like" %}'
    var options = {
      method: 'POST',
      headers: {'X-CSRFToken': csrftoken},
      mode: 'same-origin'
    }
    document.querySelector('a.like-btn')
            .addEventListener('click', function(e){
              e.preventDefault();
              var likeButton = this;
              var icon = this.querySelector('i');

              // add request body
              var formData = new FormData();
              formData.append('id', likeButton.dataset.id);
              formData.append('action', likeButton.dataset.action);
              options['body'] = formData;

              // send HTTP request
              fetch(url, options)
              .then(response => response.json())
              .then(data => {
                if (data['status'] === 'ok') {
                  var previousAction = likeButton.dataset.action;

                  // toggle button text and data-action
                  var action = previousAction === 'like' ? 'unlike' : 'like';
                  likeButton.dataset.action = action;
                  icon.classList.toggle('fa-regular');
                  icon.classList.toggle('fa-solid');

                  // update like count
                  var likeCount = document.querySelector('span.total');
                  var totalLikes = parseInt(likeCount.innerHTML);
                  likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes -1;
                }
              })
            });
{% endblock  %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Post{% endblock  %}

{% block content %}
  <div class="content-section">
    <form method="post" enctype="multipart/form-data">  
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Create Post</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group mt-3 mb-3">
        <button class="btn btn-primary me-3" name="status" value="PB" type="submit">Publish</button>
        <button class="btn btn-secondary" name="status" value="DF" type="submit">Save as Draft</button>
      </div>
    </form>
  </div>
{% endblock  %}

blog/templates/blog/readinglist.html
{% extends "blog/base.html" %}
{% load thumbnail %}

{% block content %}
<div class="mt-3">
  <h1 class="mb-3">Reading Lists</h1>
  {% for post in liked_posts %}
  <article class="media content-section d-flex">
    <img src="{% thumbnail post.author.profile.photo 300x300 crop  %}" class="rounded-circle avatar mt-2">
    <div class="media-body mx-3 mt-2">
      <h5><a class="article-title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
      <p class="mt-2">
        <span class="author">
          <a class="mt-4" href="{% url "blog:user-posts" post.author.username %}">{{ post.author.username }}</a>
        </span>
        <span class="author"> • </span>
        <small class="text-muted">{{ post.publish|date:'d M Y' }}</small>
        <span> • </span>
        <span class="text-muted">#{{ post.tags.all|join:"#"}}</span>
      </p>
    </div>
  </article>
  {% endfor %}
</div>
{% endblock  %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% load thumbnail %}

{% block content %}
<div class="mt-3">
  <h4 class="mb-3">Posts by {{posts.first.author.username}} </h4>
  {% for post in posts %}
  <article class="media content-section d-flex">
    <img src="{% thumbnail post.author.profile.photo 200x200 crop  %}" class="rounded-circle avatar mt-2">
    <div class="media-body">
      <div class="article-metadata mt-2">
        <p class="author"><a class="mt-4" href="{% url "blog:user-posts" post.author.username %}">{{ post.author.username }}</a></p>
        <small class="text-muted">{{ post.publish|date:'d M Y' }}</small>
      </div>
      <h2><a class="article-title" href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
      <p class="article-content">{{ post.content|truncatewords:30 }}</p>
    </div>
  </article>
  {% endfor %}
  {% if is_paginated %}
    {% if page_obj.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a> 
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a> 
    {% endif %}
  {% endif %}
</div>
{% endblock  %}